version: '3.7'
services:
  mysql-users-database:
    image: mysql:latest
    container_name: aipetto-users-mysql
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - ./src/datasources/mysql/data:/var/lib/mysql
    networks:
      - aipettonet
    restart: always
  go-users-service:
    env_file:
      - .env
    container_name: go-users-api
    tty: true
    build:
      context: ./
    volumes:
      - ./:/go
    environment:
      DB_SERVER: mysql-users-database
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "8081:8081"
    networks:
      - aipettonet
    depends_on:
      - "mysql-users-database"
networks:
  aipettonet:
    driver: bridge